branches:
  only:
    - master

notifications:
  email: false

language: node_js
node_js:
  - "0.12"
  - "4.2"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

after_script:
  - sleep 15
#  - CODECLIMATE_REPO_TOKEN=3ac41b4e23ebcc5ef00f749e8d111792045f651929bb23bba75396a6717522e3 ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
